### ISSUE TITLE
Shaded plot is bugged after the cmake script update

### ISSUE THREAD

**Issue by CosminPerRam** [CosminPerRam/ImGui-Visualizer#3]
Before merging the cmake script (commit cdc257269677383d6cfedd30c388c5b20ac7aaf2):
![image](https://user-images.githubusercontent.com/7972857/174996792-4fb4f7d4-983f-4134-84db-55086b6b3c76.png)
After merging (commit 6781d39e901a454181d830cde6257823bd2f8810):
![image](https://user-images.githubusercontent.com/7972857/174997311-3fe59400-08c5-4ef3-acf0-382cbcd1881b.png)

I dont really know what is causing this, I have changed the SFML version from 2.6.x back to 2.5.1 in latest but it produces the same problem. Checking out the commit before the cmake script merge makes the problem disapear, must investigate...

(Windows 10, MSVC, VS2022)

**Comment by CosminPerRam** [comment]
Seems that
```cmake
target_compile_definitions(ImPlot PUBLIC ImDrawIdx=unsigned)
```
(from `external/CMakeLists.txt`)
is not properly working, it's as if implot knows its 32 bits but imgui not, i removed this line and I manually uncommented the `ImDrawIdx` define line from `imconfig.h` and the problem is gone.

If i just try to add:
```cmake
target_compile_definitions(ImGui::ImGui PUBLIC ImDrawIdx=unsigned)
```
Cmake throws up an error saying `Cannot specify compile definitions for target "ImGui" which is not built by this project.`

If I try to add:
```cmake
add_library(ImGui
    "${imgui_SOURCE_DIR}/imgui.cpp"
    "${imgui_SOURCE_DIR}/imgui_draw.cpp"
    "${imgui_SOURCE_DIR}/imgui_tables.cpp"
    "${imgui_SOURCE_DIR}/imgui_widgets.cpp")
add_library(ImGui::ImGui ALIAS ImGui)
target_include_directories(ImGui PUBLIC "${imgui_SOURCE_DIR}")
target_compile_definitions(ImGui PUBLIC ImDrawIdx=unsigned)
target_compile_features(ImGui PUBLIC cxx_std_11)
```
it seems that the indexer is still 16-bits.
@ChrisThrasher mind telling me what is wrong with my cmake tries?

**Comment by ChrisThrasher** [comment]
I figured this might be a problem. That preprocessor definition was only applied to ImPlot and downstream targets meaning ImGui-SFML didn't get that change. Let me know if this fixes it: https://github.com/CosminPerRam/ImGui-Visualizer/commit/3724e86513715486489c9b5ed03de481261abcb6

**Comment by CosminPerRam** [comment]
Yep, it works, thanks.
I didn't knew about `add_compile_definitions`, thanks.
